# Generated by Django 4.1.4 on 2024-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallbooking',
            name='merge_or_separate',
            field=models.CharField(choices=[('Merge', 'Merge'), ('Separate', 'Separate')], max_length=100),
        ),
    ]
