# Generated by Django 4.1.4 on 2024-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0003_stallbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallbooking',
            name='stall_type',
            field=models.CharField(choices=[('National Prime', 'National Prime'), ('National General', 'National General'), ('International', 'International'), ('Agro and MSME', 'Agro and MSME'), ('Automobiles', 'Automobiles'), ('Food Stalls', 'Food Stalls'), ('BDS Providers Stall', 'BDS Providers Stall')], max_length=200),
        ),
    ]
