# Generated by Django 4.1.4 on 2024-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0004_alter_stallbooking_stall_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_type', models.CharField(choices=[('Main Sponsor', 'Main Sponsor'), ('Powered By Sponsor', 'Powered By Sponsor'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Gold', 'Gold'), ('Partner Sponsor', 'Partner Sponsor'), ('Silver', 'Silver')], max_length=200)),
                ('stall_id', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
