# Generated by Django 4.1.4 on 2025-01-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0005_sponsorbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('tour_date', models.DateField()),
                ('number_of_students', models.PositiveIntegerField()),
                ('student_level', models.CharField(choices=[('10+2', '10+2'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Mixed', 'Mixed')], default='10+2', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThematicRegistrationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('sessions', models.ManyToManyField(related_name='responses', to='cim.thematicsession')),
            ],
        ),
        migrations.CreateModel(
            name='ThematicRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('sessions', models.ManyToManyField(related_name='registrations', to='cim.thematicsession')),
            ],
        ),
    ]
