# Generated by Django 4.1.4 on 2025-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0006_guidedtour_thematicsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicregistration',
            name='food',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='hotel_accomodation',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('CIM', 'CIM')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='participant',
            field=models.CharField(choices=[('Speaker', 'Speaker'), ('Participant', 'Participant')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='travel_arrive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='travel_back_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ThematicRegistrationResponse',
        ),
    ]
