# Generated by Django 4.1.4 on 2025-01-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0010_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thematicregistration',
            old_name='travel_arrive_date',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='thematicregistration',
            old_name='travel_back_date',
            new_name='departure_date',
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='airline',
            field=models.CharField(blank=True, choices=[('Buddha', 'Buddha'), ('Yeti', 'Yeti'), ('Shree', 'Shree')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='flight_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='flight_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='hotel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='hotel_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
