# Generated by Django 4.1.4 on 2025-01-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0011_rename_travel_arrive_date_thematicregistration_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematicregistration',
            name='hotel_email',
        ),
    ]
