# Generated by Django 4.1.4 on 2025-01-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0013_alter_thematicregistration_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thematic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sessions', to='cim.thematicsession')),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Keynote Speaker', 'Keynote Speaker'), ('Moderator', 'Moderator'), ('Speaker', 'Speaker')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='panelists/')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('biodata', models.TextField()),
                ('sub_session', models.ManyToManyField(related_name='panelists', to='cim.subsession')),
            ],
        ),
    ]
