# Generated by Django 4.1.4 on 2025-01-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0014_subsession_panelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='biodata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thematicsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
