# Generated by Django 4.1.4 on 2025-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0015_alter_panelist_biodata_alter_subsession_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='role',
            field=models.CharField(choices=[('Keynote Speaker', 'Keynote Speaker'), ('Moderator', 'Moderator'), ('Speaker', 'Speaker'), ('Discussion Leader', 'Discussion Leader')], max_length=20),
        ),
    ]
