# Generated by Django 4.1.4 on 2025-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0016_alter_panelist_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
