# Generated by Django 4.1.4 on 2025-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0017_thematicregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicregistration',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
