# Generated by Django 4.1.4 on 2025-01-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0018_thematicregistration_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicregistration',
            name='airline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
