# Generated by Django 5.1.5 on 2025-01-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0019_alter_thematicregistration_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicregistration',
            name='return_flight_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thematicregistration',
            name='return_flight_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
