# Generated by Django 5.1.5 on 2025-01-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0020_thematicregistration_return_flight_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='thematic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematicpanelists', to='cim.thematicsession'),
        ),
    ]
