# Generated by Django 5.1.5 on 2025-01-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0023_alter_panelist_sub_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelist',
            name='thematic_session',
        ),
        migrations.AddField(
            model_name='panelist',
            name='thematic_session',
            field=models.ManyToManyField(blank=True, related_name='thematicpanelists', to='cim.thematicsession'),
        ),
    ]
