# Generated by Django 5.1.5 on 2025-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0024_remove_panelist_thematic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='role',
            field=models.CharField(choices=[('Keynote Speaker', 'Keynote Speaker'), ('Theme Chair', 'Theme Chair'), ('Moderator', 'Moderator'), ('Chief Guest', 'Chief Guest'), ('Guest of Honour', 'Guest of Honour'), ('Speaker', 'Speaker'), ('Discussion Leader', 'Discussion Leader')], max_length=20),
        ),
    ]
