# Generated by Django 5.1.5 on 2025-01-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0025_alter_panelist_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='role',
            field=models.CharField(choices=[('Keynote Speaker', 'Keynote Speaker'), ('Theme Chair', 'Theme Chair'), ('Moderator', 'Moderator'), ('Chief Guest', 'Chief Guest'), ('Guest of Honor', 'Guest of Honor'), ('Speaker', 'Speaker'), ('Guest', 'Guest'), ('Discussion Leader', 'Discussion Leader')], max_length=20),
        ),
    ]
