# Generated by Django 5.1.5 on 2025-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0026_alter_panelist_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='role',
            field=models.CharField(choices=[('Theme Chair', 'Theme Chair'), ('Chief Guest', 'Chief Guest'), ('Guest of Honor', 'Guest of Honor'), ('Moderator', 'Moderator'), ('Keynote Speaker', 'Keynote Speaker'), ('Speaker', 'Speaker'), ('Guest', 'Guest'), ('Discussion Leader', 'Discussion Leader'), ('Presenter', 'Presenter')], max_length=20),
        ),
    ]
