# Generated by Django 5.1.5 on 2025-03-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cim', '0028_delete_guidedtour_delete_invitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('tour_date', models.DateField()),
                ('number_of_students', models.PositiveIntegerField()),
                ('student_level', models.CharField(choices=[('10+2', '10+2'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Mixed', 'Mixed')], default='10+2', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='ACCEPTED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_type', models.CharField(choices=[('Main Sponsor', 'Main Sponsor'), ('Powered By Sponsor', 'Powered By Sponsor'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Gold', 'Gold'), ('Partner Sponsor', 'Partner Sponsor'), ('Silver', 'Silver')], max_length=200)),
                ('stall_id', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('chief_executive', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('stall_type', models.CharField(choices=[('National Prime', 'National Prime'), ('National General', 'National General'), ('International', 'International'), ('Agro and MSME', 'Agro and MSME'), ('Automobiles', 'Automobiles'), ('Food Stalls', 'Food Stalls'), ('BDS Providers Stall', 'BDS Providers Stall')], max_length=200)),
                ('stall_no', models.CharField(max_length=200)),
                ('merge_or_separate', models.CharField(choices=[('Merge', 'Merge'), ('Separate', 'Separate')], max_length=100)),
                ('voucher', models.FileField(upload_to='vouchers/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_words', models.TextField()),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stall Booking',
                'verbose_name_plural': 'Stall Bookings',
            },
        ),
        migrations.CreateModel(
            name='ThematicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('participant', models.CharField(choices=[('Speaker', 'Speaker'), ('Participant', 'Participant')], max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('flight_no', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_time', models.TimeField(blank=True, null=True)),
                ('return_flight_no', models.CharField(blank=True, max_length=20, null=True)),
                ('return_flight_time', models.TimeField(blank=True, null=True)),
                ('airline', models.CharField(blank=True, max_length=50, null=True)),
                ('food', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], max_length=20, null=True)),
                ('hotel_accomodation', models.CharField(blank=True, choices=[('Self', 'Self'), ('CIM', 'CIM')], max_length=20, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('hotel', models.CharField(blank=True, max_length=220, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('sessions', models.ManyToManyField(related_name='registrations', to='cim.thematicsession')),
            ],
        ),
        migrations.CreateModel(
            name='SubSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thematic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sessions', to='cim.thematicsession')),
            ],
        ),
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Theme Chair', 'Theme Chair'), ('Chief Guest', 'Chief Guest'), ('Guest of Honor', 'Guest of Honor'), ('Moderator', 'Moderator'), ('Keynote Speaker', 'Keynote Speaker'), ('Speaker', 'Speaker'), ('Guest', 'Guest'), ('Discussion Leader', 'Discussion Leader'), ('Presenter', 'Presenter')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='panelists/')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('biodata', models.TextField(blank=True, null=True)),
                ('sub_session', models.ManyToManyField(blank=True, related_name='panelists', to='cim.subsession')),
                ('thematic_session', models.ManyToManyField(blank=True, related_name='thematicpanelists', to='cim.thematicsession')),
            ],
        ),
    ]
