# Generated by Django 5.1.5 on 2025-03-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cim', '0029_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuidedTour',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='sub_session',
        ),
        migrations.RemoveField(
            model_name='panelist',
            name='thematic_session',
        ),
        migrations.DeleteModel(
            name='SponsorBooking',
        ),
        migrations.DeleteModel(
            name='StallBooking',
        ),
        migrations.RemoveField(
            model_name='subsession',
            name='thematic_session',
        ),
        migrations.RemoveField(
            model_name='thematicregistration',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='Panelist',
        ),
        migrations.DeleteModel(
            name='SubSession',
        ),
        migrations.DeleteModel(
            name='ThematicRegistration',
        ),
        migrations.DeleteModel(
            name='ThematicSession',
        ),
    ]
