# Generated by Django 5.1.5 on 2025-03-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0003_blogcategory_blogtag_blog_category_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='thumbnail_image_alt_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
