# Generated by Django 5.1.5 on 2025-03-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0004_service_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='service',
            new_name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='catalogue',
            field=models.FileField(blank=True, null=True, upload_to='catalogue/'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_image_alt_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
