# Generated by Django 5.1.5 on 2025-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0007_alter_blog_slug_alter_blogcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='team/'),
        ),
    ]
