# Generated by Django 5.1.5 on 2025-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0008_alter_teammember_designation_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='baliyo.blogtag'),
        ),
    ]
