# Generated by Django 5.1.5 on 2025-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0010_department_ourpartner_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='image_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
