# Generated by Django 5.1.5 on 2025-03-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0012_gallery_delete_imagegallery_remove_image_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt_description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='baliyo.project'),
            preserve_default=False,
        ),
    ]
