# Generated by Django 5.1.5 on 2026-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0015_alter_blog_slug_alter_blogcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(choices=[('baliyoventures', 'Baliyo Ventures'), ('baliyotechnologies', 'Baliyo Technologies')], default='baliyoventures', max_length=255),
        ),
    ]
