# Generated by Django 5.1.5 on 2026-04-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0016_contact_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(choices=[('baliyoventures', 'baliyoventures'), ('baliyotechnologies', 'baliyotechnologies')], default='baliyoventures', max_length=255),
        ),
    ]
