# Generated by Django 5.1.5 on 2026-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0017_alter_contact_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_contact_number', models.CharField(max_length=255)),
                ('employee_email', models.CharField(max_length=255)),
                ('reason_of_leave', models.CharField(choices=[('paid', 'paid'), ('sick', 'Sick'), ('unpaid', 'unpaid'), ('weekly', 'weekly'), ('other', 'other')], max_length=255)),
                ('brief_reason', models.TextField()),
                ('days', models.IntegerField()),
                ('leave_from_date', models.DateField()),
                ('leave_to_date', models.DateField()),
                ('approved_by', models.CharField(choices=[('anil', 'anil'), ('prithvi', 'prithvi'), ('manav', 'manav'), ('sapana', 'sapana')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
