# Generated by Django 5.1.5 on 2026-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0018_leaveform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='approved_by',
            field=models.CharField(choices=[('Anil Singh', 'Anil Singh'), ('Prithvi Chaudhary', 'Prithvi Chaudhary'), ('Manav Dahal', 'Manav Dahal'), ('Sapana Dhakal', 'Sapana Dhakal')], max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='reason_of_leave',
            field=models.CharField(choices=[('paid', 'Paid'), ('sick', 'Sick'), ('unpaid', 'Unpaid'), ('weekly', 'Weekly'), ('other', 'Other')], max_length=255),
        ),
    ]
