# Generated by Django 5.1.5 on 2026-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0019_alter_leaveform_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='approved_by',
            field=models.CharField(choices=[('Anil Singh', 'Anil Singh'), ('Prithvi Chaudhary', 'Prithvi Chaudhary'), ('Manav Khadka', 'Manav Khadka'), ('Sapana Dhakal', 'Sapana Dhakal')], max_length=255),
        ),
    ]
