# Generated by Django 5.1.5 on 2026-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0021_project_case_study_project_problem_it_solves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
