# Generated by Django 5.1.5 on 2026-07-22 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0022_teammember_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_technical_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_documents', to='baliyo.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectRenderingImage',
        ),
    ]
