# Generated by Django 5.1.5 on 2026-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0026_component_vendor_projecttool_slug_componentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdemo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicaldocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
