# Generated by Django 5.1.5 on 2026-07-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0027_projectdemo_name_technicaldocument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_per_item', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='componentpurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='componentpurchase',
            name='component_model',
        ),
        migrations.RemoveField(
            model_name='componentpurchase',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='componentpurchase',
            name='quantity',
        ),
        migrations.AddField(
            model_name='componentpurchase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentpurchase',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentpurchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='baliyo.vendor'),
        ),
        migrations.AlterField(
            model_name='componentpurchase',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddIndex(
            model_name='componentpurchase',
            index=models.Index(fields=['vendor', 'purchase_date'], name='baliyo_comp_vendor__8896b5_idx'),
        ),
        migrations.AddField(
            model_name='componentpurchaseitem',
            name='component_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='baliyo.componentmodel'),
        ),
        migrations.AddField(
            model_name='componentpurchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baliyo.componentpurchase'),
        ),
    ]
