# Generated by Django 5.1.5 on 2026-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0028_componentpurchaseitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdailyupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=50),
        ),
    ]
