# Generated by Django 5.1.5 on 2026-07-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0029_alter_projectdailyupdate_options_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttool',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
