# Generated by Django 5.1.5 on 2026-07-28 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0030_projecttool_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.CreateModel(
            name='ProjectToolUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_used', to='baliyo.project')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_used', to='baliyo.projecttool')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'tool'], name='baliyo_proj_project_ec360c_idx')],
                'unique_together': {('project', 'tool')},
            },
        ),
    ]
