# Generated by Django 5.1.5 on 2026-07-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0031_remove_project_tools_projecttoolused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('published', 'Published')], db_index=True, default='in_progress', max_length=50),
        ),
    ]
