# Generated by Django 5.1.5 on 2026-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0032_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpurchase',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to='component_purchase_bills/'),
        ),
    ]
