# Generated by Django 5.1.5 on 2026-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0033_componentpurchase_bill_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
