# Generated by Django 5.1.5 on 2026-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0034_projectorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpurchaseitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pcs'), ('kg', 'Kg'), ('m', 'Meter')], default='pcs', max_length=20),
        ),
    ]
