# Generated by Django 5.1.5 on 2026-08-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyo', '0036_alter_componentpurchaseitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpurchase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_purchases', to='baliyo.project'),
        ),
        migrations.AddIndex(
            model_name='componentpurchase',
            index=models.Index(fields=['project'], name='baliyo_comp_project_6146f3_idx'),
        ),
    ]
