# Generated by Django 4.1.4 on 2024-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('register_as_a', models.CharField(choices=[('Investor', 'Investor'), ('Stakeholder', 'Stakeholder'), ('Learner', 'Learner'), ('Visitor', 'Visitor')], default='Visitor', max_length=100)),
                ('area_of_interest', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('arrival_date', models.DateField(blank=True)),
                ('departure_date', models.DateField(blank=True)),
                ('accomodation_required', models.BooleanField(default=False)),
                ('hotel_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
