<<<<<<< HEAD
# Generated by Django 4.1.4 on 2024-12-29 09:00
=======
# Generated by Django 4.1.4 on 2024-12-19 03:08
>>>>>>> e914e7a2950d26d3124bc601cba75f2ecca810ad

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
<<<<<<< HEAD
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales', 'Sales'), ('Customer', 'Customer')], max_length=255),
=======
            field=models.CharField(choices=[('Customer', 'Customer'), ('Sales', 'Sales'), ('Admin', 'Admin')], max_length=255),
>>>>>>> e914e7a2950d26d3124bc601cba75f2ecca810ad
        ),
    ]
