# Generated by Django 4.1.4 on 2025-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Sales', 'Sales')], max_length=255),
        ),
    ]
