# Generated by Django 4.1.4 on 2025-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Customer', 'Customer'), ('Admin', 'Admin')], max_length=255),
        ),
    ]
