# Generated by Django 5.1.5 on 2025-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Admin', 'Admin'), ('Customer', 'Customer')], max_length=255),
        ),
    ]
