# Generated by Django 5.1.5 on 2025-05-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_organization_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='transaction_type',
        ),
    ]
