# Generated by Django 5.1.5 on 2025-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_remove_organization_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
