# Generated by Django 5.1.5 on 2025-06-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_organizationcontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontacts',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.organization'),
        ),
    ]
