# Generated by Django 5.1.5 on 2025-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_projectnotes_projectreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreminder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
