# Generated by Django 5.1.5 on 2025-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
