# Generated by Django 5.1.5 on 2025-07-28 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_franchise_slug_alter_franchise_address_and_more'),
        ('blog', '0002_alter_post_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.franchise'),
        ),
    ]
