# Generated by Django 5.1.5 on 2025-05-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='transaction_type',
            field=models.CharField(choices=[('Receivable', 'Receivable'), ('Payable', 'Payable'), ('Received', 'Received'), ('Paid', 'Paid')], max_length=10),
        ),
    ]
