# Generated by Django 5.1.5 on 2025-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0002_alter_financerecord_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
