# Generated by Django 5.1.5 on 2025-05-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_department'),
        ('finance_management', '0004_department_stock_financerecord_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='stock',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
