# Generated by Django 5.1.5 on 2025-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0005_alter_financerecord_department_stock_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='product_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
