# Generated by Django 5.1.5 on 2025-05-28 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0006_stock_price_stock_product_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance_management.financerecord')),
            ],
            options={
                'verbose_name_plural': 'Finance Record Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
