# Generated by Django 5.1.5 on 2025-05-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_department'),
        ('finance_management', '0008_financerecord_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
