# Generated by Django 5.1.5 on 2025-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0009_alter_financerecord_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='related_record',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='tags',
            field=models.ManyToManyField(blank=True, to='finance_management.tag'),
        ),
    ]
