# Generated by Django 5.1.5 on 2025-05-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0011_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='include_words_total',
        ),
    ]
