# Generated by Django 5.1.5 on 2025-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0012_remove_invoice_include_words_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], max_length=10, null=True),
        ),
    ]
