# Generated by Django 5.1.5 on 2025-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0013_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
