# Generated by Django 5.1.5 on 2025-05-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0014_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='invoice_signatures/'),
        ),
    ]
