# Generated by Django 5.1.5 on 2025-05-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0015_alter_invoice_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax',
            new_name='vat',
        ),
    ]
