# Generated by Django 5.1.5 on 2025-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0016_rename_tax_invoice_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=10),
        ),
    ]
