# Generated by Django 5.1.5 on 2025-06-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_project'),
        ('finance_management', '0018_financerecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecord',
            name='organization',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
    ]
