# Generated by Django 5.1.5 on 2025-06-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0019_remove_financerecord_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecord',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
