# Generated by Django 5.1.5 on 2025-06-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_project_slug'),
        ('finance_management', '0020_remove_financerecord_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
