# Generated by Django 5.1.5 on 2025-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0021_financerecord_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
