# Generated by Django 4.1.4 on 2024-04-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='avatar',
            new_name='after',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='before',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
