# Generated by Django 5.1.5 on 2026-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_options_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_bhumi',
            field=models.BooleanField(default=False),
        ),
    ]
