# Generated by Django 5.1.5 on 2025-12-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aidata',
            old_name='ai_data',
            new_name='ai_json_data',
        ),
    ]
