# Generated by Django 5.1.5 on 2025-12-07 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_data', '0002_rename_ai_data_aidata_ai_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidata',
            name='conversation_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidata',
            name='extracted_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
