# Generated by Django 5.1.4 on 2024-12-17 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('GROUP', 'GROUP'), ('EXPO_ACCESS', 'EXPO_ACCESS'), ('SINGLE_PERSON', 'SINGLE_PERSON')], max_length=20)),
                ('total_participants', models.IntegerField(choices=[('2', '2'), ('1', '1'), ('3', '3'), ('5', '5'), ('4', '4')])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Nabil_Bank', 'Nabil_Bank')], max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('is_early_bird', models.BooleanField(default=False)),
                ('is_expo_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('10+2', '10+2'), ('Under SEE', 'Under SEE')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(14)])),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('is_free_entry', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rojgar_pavillion.registration')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_participants', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rojgar_pavillion.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_participants', models.IntegerField(default=0)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rojgar_pavillion.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rojgar_pavillion.trainingsession'),
        ),
    ]
