# Generated by Django 5.1.4 on 2024-12-17 07:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='agreed_to_no_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='qualification',
            field=models.CharField(choices=[('Under SEE', 'Under SEE'), ('10+2', '10+2'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('Nabil_Bank', 'Nabil Bank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('SINGLE', 'Single Person'), ('GROUP', 'Group'), ('EXPO_ACCESS', 'Expo Access')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='rojgar_pavillion.topic'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='rojgar_pavillion.timeslot'),
        ),
    ]
