# Generated by Django 4.1.4 on 2024-12-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0002_registration_group_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='group_members',
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('Nabil Bank', 'Nabil Bank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('Single Person', 'Single Person'), ('Group', 'Group'), ('Expo Access', 'Expo Access')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
