# Generated by Django 5.1.4 on 2024-12-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0002_registration_agreed_to_no_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
