# Generated by Django 5.1.4 on 2024-12-17 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0003_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='training_session',
        ),
        migrations.AddField(
            model_name='registration',
            name='time_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rojgar_pavillion.timeslot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='current_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
