# Generated by Django 4.1.4 on 2024-12-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0003_remove_registration_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='group_members',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_screenshot',
            field=models.ImageField(upload_to='payments/'),
        ),
    ]
