# Generated by Django 4.1.4 on 2024-12-19 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0005_alter_registration_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
