# Generated by Django 4.1.4 on 2024-12-19 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0006_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
