# Generated by Django 4.1.4 on 2024-12-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0007_alter_registration_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_instances', to='rojgar_pavillion.topic'),
        ),
    ]
