# Generated by Django 4.1.4 on 2024-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0008_topic_time_slots_alter_timeslot_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='full_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
