# Generated by Django 5.1.5 on 2025-01-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgar_pavillion', '0010_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_attended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
