# Generated by Django 5.1.5 on 2026-08-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0014_instantorder_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=100)),
                ('api_username', models.CharField(max_length=100)),
                ('api_password', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NPS Configuration',
                'verbose_name_plural': 'NPS Configurations',
            },
        ),
        migrations.CreateModel(
            name='NPSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_txn_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('process_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Fail', 'Fail')], db_index=True, default='Pending', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=150, null=True)),
                ('instrument', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_remarks', models.TextField(blank=True, null=True)),
                ('cbs_message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='nps_payment_status_a47610_idx'), models.Index(fields=['merchant_txn_id'], name='nps_payment_merchan_40f7fd_idx')],
            },
        ),
    ]
