# Generated by Django 5.1.5 on 2026-08-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_franchise_slug_alter_franchise_address_and_more'),
        ('nps_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npsconfig',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nps_configs', to='about.franchise'),
        ),
    ]
