# Generated by Django 5.1 on 2025-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('yachu_facewash_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yachu_bodylotion_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yachu_brightening_cream_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Guess',
                'verbose_name_plural': 'Price Guesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
