# Generated by Django 5.1.5 on 2025-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_guess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceguess',
            name='yachu_bodylotion_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='priceguess',
            name='yachu_brightening_cream_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='priceguess',
            name='yachu_facewash_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
