# Generated by Django 5.1 on 2025-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=255)),
                ('key', models.CharField(help_text='The actual API key value', max_length=500, unique=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this key has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key should be included in rotation')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of last use', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['last_used_at', 'created_at'],
            },
        ),
    ]
