# Generated by Django 5.1.5 on 2025-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, help_text='Descriptive name for the API key', max_length=255, null=True),
        ),
    ]
