# Generated by Django 5.1.5 on 2025-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_alter_apikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='usage_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of times this key has been used', null=True),
        ),
    ]
