# Generated by Django 4.1.4 on 2024-09-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_location', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.IntegerField()),
                ('alternate_phone_number', models.IntegerField(blank=True, null=True)),
                ('delivery_charge', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Prepaid', 'Prepaid')], max_length=255)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('order_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('shampoo', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convinced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convinced_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dandruff Case', 'Dandruff Case'), ('Hairfall Case', 'Hairfall Case'), ('Baldness Case', 'Baldness Case'), ('Shampoo Bottle', 'Shampoo Bottle'), ('Shampoo sashe pack of 10', 'Shampoo sashe pack of 10')], max_length=255)),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order')),
            ],
        ),
    ]
