# Generated by Django 5.1.5 on 2025-12-19 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_instantorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instantorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
