# Generated by Django 5.1.5 on 2025-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_instantorder_created_at_instantorder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
