# Generated by Django 5.1.5 on 2026-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_is_paid_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('NPS', 'Nepal Payment Solution')], db_index=True, default='COD', max_length=50),
        ),
    ]
